/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesIndexRouteImport } from './routes/examples.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ExamplesRoutePlanningRouteImport } from './routes/examples.route-planning'
import { Route as ExamplesPropertySearchRouteImport } from './routes/examples.property-search'
import { Route as ExamplesMarkerGroupMoveRouteImport } from './routes/examples.marker-group-move'
import { Route as ExamplesMapSectionDownloadRouteImport } from './routes/examples.map-section-download'
import { Route as ExamplesHeatmapDensityRouteImport } from './routes/examples.heatmap-density'
import { Route as ExamplesGeoFencingRouteImport } from './routes/examples.geo-fencing'
import { Route as ExamplesDeliveryZoneRouteImport } from './routes/examples.delivery-zone'
import { Route as ExamplesBatchGeocodingRouteImport } from './routes/examples.batch-geocoding'
import { Route as DocsStylingRouteImport } from './routes/docs.styling'
import { Route as DocsMobileSelectionRouteImport } from './routes/docs.mobile-selection'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsExternalControllerRouteImport } from './routes/docs.external-controller'
import { Route as DocsBasicRouteImport } from './routes/docs.basic'
import { Route as DocsApiRouteImport } from './routes/docs.api'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoutePlanningRoute = ExamplesRoutePlanningRouteImport.update({
  id: '/examples/route-planning',
  path: '/examples/route-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPropertySearchRoute = ExamplesPropertySearchRouteImport.update({
  id: '/examples/property-search',
  path: '/examples/property-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMarkerGroupMoveRoute = ExamplesMarkerGroupMoveRouteImport.update({
  id: '/examples/marker-group-move',
  path: '/examples/marker-group-move',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMapSectionDownloadRoute =
  ExamplesMapSectionDownloadRouteImport.update({
    id: '/examples/map-section-download',
    path: '/examples/map-section-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesHeatmapDensityRoute = ExamplesHeatmapDensityRouteImport.update({
  id: '/examples/heatmap-density',
  path: '/examples/heatmap-density',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesGeoFencingRoute = ExamplesGeoFencingRouteImport.update({
  id: '/examples/geo-fencing',
  path: '/examples/geo-fencing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesDeliveryZoneRoute = ExamplesDeliveryZoneRouteImport.update({
  id: '/examples/delivery-zone',
  path: '/examples/delivery-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesBatchGeocodingRoute = ExamplesBatchGeocodingRouteImport.update({
  id: '/examples/batch-geocoding',
  path: '/examples/batch-geocoding',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStylingRoute = DocsStylingRouteImport.update({
  id: '/docs/styling',
  path: '/docs/styling',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMobileSelectionRoute = DocsMobileSelectionRouteImport.update({
  id: '/docs/mobile-selection',
  path: '/docs/mobile-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsExternalControllerRoute = DocsExternalControllerRouteImport.update({
  id: '/docs/external-controller',
  path: '/docs/external-controller',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBasicRoute = DocsBasicRouteImport.update({
  id: '/docs/basic',
  path: '/docs/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/basic': typeof DocsBasicRoute
  '/docs/external-controller': typeof DocsExternalControllerRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mobile-selection': typeof DocsMobileSelectionRoute
  '/docs/styling': typeof DocsStylingRoute
  '/examples/batch-geocoding': typeof ExamplesBatchGeocodingRoute
  '/examples/delivery-zone': typeof ExamplesDeliveryZoneRoute
  '/examples/geo-fencing': typeof ExamplesGeoFencingRoute
  '/examples/heatmap-density': typeof ExamplesHeatmapDensityRoute
  '/examples/map-section-download': typeof ExamplesMapSectionDownloadRoute
  '/examples/marker-group-move': typeof ExamplesMarkerGroupMoveRoute
  '/examples/property-search': typeof ExamplesPropertySearchRoute
  '/examples/route-planning': typeof ExamplesRoutePlanningRoute
  '/docs/': typeof DocsIndexRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/basic': typeof DocsBasicRoute
  '/docs/external-controller': typeof DocsExternalControllerRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mobile-selection': typeof DocsMobileSelectionRoute
  '/docs/styling': typeof DocsStylingRoute
  '/examples/batch-geocoding': typeof ExamplesBatchGeocodingRoute
  '/examples/delivery-zone': typeof ExamplesDeliveryZoneRoute
  '/examples/geo-fencing': typeof ExamplesGeoFencingRoute
  '/examples/heatmap-density': typeof ExamplesHeatmapDensityRoute
  '/examples/map-section-download': typeof ExamplesMapSectionDownloadRoute
  '/examples/marker-group-move': typeof ExamplesMarkerGroupMoveRoute
  '/examples/property-search': typeof ExamplesPropertySearchRoute
  '/examples/route-planning': typeof ExamplesRoutePlanningRoute
  '/docs': typeof DocsIndexRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/basic': typeof DocsBasicRoute
  '/docs/external-controller': typeof DocsExternalControllerRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mobile-selection': typeof DocsMobileSelectionRoute
  '/docs/styling': typeof DocsStylingRoute
  '/examples/batch-geocoding': typeof ExamplesBatchGeocodingRoute
  '/examples/delivery-zone': typeof ExamplesDeliveryZoneRoute
  '/examples/geo-fencing': typeof ExamplesGeoFencingRoute
  '/examples/heatmap-density': typeof ExamplesHeatmapDensityRoute
  '/examples/map-section-download': typeof ExamplesMapSectionDownloadRoute
  '/examples/marker-group-move': typeof ExamplesMarkerGroupMoveRoute
  '/examples/property-search': typeof ExamplesPropertySearchRoute
  '/examples/route-planning': typeof ExamplesRoutePlanningRoute
  '/docs/': typeof DocsIndexRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/api'
    | '/docs/basic'
    | '/docs/external-controller'
    | '/docs/installation'
    | '/docs/mobile-selection'
    | '/docs/styling'
    | '/examples/batch-geocoding'
    | '/examples/delivery-zone'
    | '/examples/geo-fencing'
    | '/examples/heatmap-density'
    | '/examples/map-section-download'
    | '/examples/marker-group-move'
    | '/examples/property-search'
    | '/examples/route-planning'
    | '/docs/'
    | '/examples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/api'
    | '/docs/basic'
    | '/docs/external-controller'
    | '/docs/installation'
    | '/docs/mobile-selection'
    | '/docs/styling'
    | '/examples/batch-geocoding'
    | '/examples/delivery-zone'
    | '/examples/geo-fencing'
    | '/examples/heatmap-density'
    | '/examples/map-section-download'
    | '/examples/marker-group-move'
    | '/examples/property-search'
    | '/examples/route-planning'
    | '/docs'
    | '/examples'
  id:
    | '__root__'
    | '/'
    | '/docs/api'
    | '/docs/basic'
    | '/docs/external-controller'
    | '/docs/installation'
    | '/docs/mobile-selection'
    | '/docs/styling'
    | '/examples/batch-geocoding'
    | '/examples/delivery-zone'
    | '/examples/geo-fencing'
    | '/examples/heatmap-density'
    | '/examples/map-section-download'
    | '/examples/marker-group-move'
    | '/examples/property-search'
    | '/examples/route-planning'
    | '/docs/'
    | '/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsBasicRoute: typeof DocsBasicRoute
  DocsExternalControllerRoute: typeof DocsExternalControllerRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsMobileSelectionRoute: typeof DocsMobileSelectionRoute
  DocsStylingRoute: typeof DocsStylingRoute
  ExamplesBatchGeocodingRoute: typeof ExamplesBatchGeocodingRoute
  ExamplesDeliveryZoneRoute: typeof ExamplesDeliveryZoneRoute
  ExamplesGeoFencingRoute: typeof ExamplesGeoFencingRoute
  ExamplesHeatmapDensityRoute: typeof ExamplesHeatmapDensityRoute
  ExamplesMapSectionDownloadRoute: typeof ExamplesMapSectionDownloadRoute
  ExamplesMarkerGroupMoveRoute: typeof ExamplesMarkerGroupMoveRoute
  ExamplesPropertySearchRoute: typeof ExamplesPropertySearchRoute
  ExamplesRoutePlanningRoute: typeof ExamplesRoutePlanningRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/route-planning': {
      id: '/examples/route-planning'
      path: '/examples/route-planning'
      fullPath: '/examples/route-planning'
      preLoaderRoute: typeof ExamplesRoutePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/property-search': {
      id: '/examples/property-search'
      path: '/examples/property-search'
      fullPath: '/examples/property-search'
      preLoaderRoute: typeof ExamplesPropertySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/marker-group-move': {
      id: '/examples/marker-group-move'
      path: '/examples/marker-group-move'
      fullPath: '/examples/marker-group-move'
      preLoaderRoute: typeof ExamplesMarkerGroupMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/map-section-download': {
      id: '/examples/map-section-download'
      path: '/examples/map-section-download'
      fullPath: '/examples/map-section-download'
      preLoaderRoute: typeof ExamplesMapSectionDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/heatmap-density': {
      id: '/examples/heatmap-density'
      path: '/examples/heatmap-density'
      fullPath: '/examples/heatmap-density'
      preLoaderRoute: typeof ExamplesHeatmapDensityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/geo-fencing': {
      id: '/examples/geo-fencing'
      path: '/examples/geo-fencing'
      fullPath: '/examples/geo-fencing'
      preLoaderRoute: typeof ExamplesGeoFencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/delivery-zone': {
      id: '/examples/delivery-zone'
      path: '/examples/delivery-zone'
      fullPath: '/examples/delivery-zone'
      preLoaderRoute: typeof ExamplesDeliveryZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/batch-geocoding': {
      id: '/examples/batch-geocoding'
      path: '/examples/batch-geocoding'
      fullPath: '/examples/batch-geocoding'
      preLoaderRoute: typeof ExamplesBatchGeocodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/styling': {
      id: '/docs/styling'
      path: '/docs/styling'
      fullPath: '/docs/styling'
      preLoaderRoute: typeof DocsStylingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mobile-selection': {
      id: '/docs/mobile-selection'
      path: '/docs/mobile-selection'
      fullPath: '/docs/mobile-selection'
      preLoaderRoute: typeof DocsMobileSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/external-controller': {
      id: '/docs/external-controller'
      path: '/docs/external-controller'
      fullPath: '/docs/external-controller'
      preLoaderRoute: typeof DocsExternalControllerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/basic': {
      id: '/docs/basic'
      path: '/docs/basic'
      fullPath: '/docs/basic'
      preLoaderRoute: typeof DocsBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsApiRoute: DocsApiRoute,
  DocsBasicRoute: DocsBasicRoute,
  DocsExternalControllerRoute: DocsExternalControllerRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsMobileSelectionRoute: DocsMobileSelectionRoute,
  DocsStylingRoute: DocsStylingRoute,
  ExamplesBatchGeocodingRoute: ExamplesBatchGeocodingRoute,
  ExamplesDeliveryZoneRoute: ExamplesDeliveryZoneRoute,
  ExamplesGeoFencingRoute: ExamplesGeoFencingRoute,
  ExamplesHeatmapDensityRoute: ExamplesHeatmapDensityRoute,
  ExamplesMapSectionDownloadRoute: ExamplesMapSectionDownloadRoute,
  ExamplesMarkerGroupMoveRoute: ExamplesMarkerGroupMoveRoute,
  ExamplesPropertySearchRoute: ExamplesPropertySearchRoute,
  ExamplesRoutePlanningRoute: ExamplesRoutePlanningRoute,
  DocsIndexRoute: DocsIndexRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
